# Generated by Django 4.2.27 on 2025-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentchunk',
            name='meta_info',
            field=models.JSONField(default=dict, verbose_name='元数据详情'),
        ),
    ]
