# Generated by Django 4.2.27 on 2025-12-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_documentchunk_meta_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(default='未命名文档', max_length=255, verbose_name='原始文件名'),
        ),
    ]
