# Generated by Django 4.2.27 on 2025-12-15 10:36

import django.contrib.postgres.indexes
from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_chatsession_chatmessage'),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='documentchunk',
            index=django.contrib.postgres.indexes.GinIndex(fields=['content'], name='chunk_content_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
