# Generated by Django 4.2.27 on 2025-12-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_documentchunk_chunk_content_gin_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='文档摘要'),
        ),
    ]
