# Generated by Django 4.2.27 on 2025-12-18 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0007_remove_chatsession_owner_id_chatsession_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', '等待处理'), ('reviewing', '待审核'), ('active', '已发布'), ('failed', '处理失败')], default='pending', max_length=20, verbose_name='状态'),
        ),
    ]
