# Generated by Django 4.2.27 on 2025-12-19 18:40

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_document_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=core.models.user_directory_path, verbose_name='文件'),
        ),
    ]
