# Generated by Django 4.2.27 on 2025-12-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='feedback_comment',
            field=models.TextField(blank=True, null=True, verbose_name='反馈备注'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='评分'),
        ),
    ]
