# Generated by Django 4.2.27 on 2025-12-21 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_chatmessage_feedback_comment_chatmessage_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='session_type',
            field=models.CharField(choices=[('rag', '知识库对话'), ('agent', '全能智能体')], default='rag', max_length=10, verbose_name='会话类型'),
        ),
    ]
